---
version: "2.0"
services:
  redis:
    image: redis:7-alpine
    expose:
      - port: 6379
        as: 6379
        to:
          - global: false
          - service: smoothsend-relayer
  smoothsend-relayer:
    image: ivedmohan/smoothsend-backend
    expose:
      - port: 3000
        as: 443
        accept:
          - smoothsend.xyz
        to:
          - global: true
    env:
      - NODE_ENV=production
      - PORT=3000
      - APTOS_NETWORK=testnet
      - >-
        RELAYER_PRIVATE_KEY=[hidden]
      - >-
        CONTRACT_ADDRESS=0x6d88ee2fde204e756874e13f5d5eddebd50725805c0a332ade87d1ef03f9148b
      - PYTH_HERMES_URL=https://hermes.pyth.network
      - APTOS_RPC_URL=https://api.testnet.aptoslabs.com/v1
      - FEE_MARKUP_PERCENTAGE=10
      - MIN_APT_BALANCE=1000000000
      - MAX_TRANSACTION_AMOUNT=1000000000
      - >-
        TREASURY_ADDRESS=[hidden]
      - LOG_LEVEL=info
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX_REQUESTS=100
      - DATABASE_URL=sqlite:./data/smoothsend.db
      - REDIS_URL=redis://redis:6379
profiles:
  compute:
    redis:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 256Mi
        storage:
          - size: 512Mi
    smoothsend-relayer:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        redis:
          denom: uakt
          amount: 100000
        smoothsend-relayer:
          denom: uakt
          amount: 8000
deployment:
  redis:
    dcloud:
      profile: redis
      count: 1
  smoothsend-relayer:
    dcloud:
      profile: smoothsend-relayer
      count: 1
