#!/bin/bash

# SmoothSend Deployment Guide

echo "🚀 SmoothSend Deployment Guide"
echo "================================"

echo ""
echo "📦 BACKEND DEPLOYMENT (Azure App Service)"
echo "----------------------------------------"
echo "1. Create Azure App Service:"
echo "   - Go to Azure Portal"
echo "   - Create new App Service"
echo "   - Runtime: Node.js 18"
echo "   - Region: Choose closest to your users"
echo ""
echo "2. Configure Environment Variables in Azure:"
echo "   - Go to App Service -> Configuration -> Application Settings"
echo "   - Add all variables from azure-env-template.txt"
echo ""
echo "3. Set up Azure Database for PostgreSQL:"
echo "   - Create Azure Database for PostgreSQL flexible server"
echo "   - Update DATABASE_URL in app settings"
echo ""
echo "4. Set up Azure Cache for Redis:"
echo "   - Create Azure Cache for Redis"
echo "   - Update REDIS_URL in app settings"
echo ""
echo "5. Deploy using Git:"
echo "   cd /home/ved-mohan/Desktop/smoothsendxyz"
echo "   git remote add azure https://\$username@your-app.scm.azurewebsites.net:443/your-app.git"
echo "   git push azure main"
echo ""

echo "🌐 FRONTEND DEPLOYMENT (Vercel)"
echo "-------------------------------"
echo "1. Install Vercel CLI:"
echo "   npm i -g vercel"
echo ""
echo "2. Deploy from frontend directory:"
echo "   cd smoothsend-frontend"
echo "   vercel --prod"
echo ""
echo "3. Configure Environment Variables in Vercel:"
echo "   - Go to Vercel Dashboard -> Project -> Settings -> Environment Variables"
echo "   - Add all variables from vercel-env-template.txt"
echo "   - Update NEXT_PUBLIC_API_URL with your Azure backend URL"
echo ""

echo "✅ VERIFICATION STEPS"
echo "--------------------"
echo "1. Test backend health: https://your-azure-backend.azurewebsites.net/health"
echo "2. Test frontend: https://your-frontend.vercel.app"
echo "3. Test full flow: Transfer USDC through the UI"
echo ""

echo "📝 IMPORTANT NOTES"
echo "------------------"
echo "- Make sure to update CORS_ORIGIN in Azure to match your Vercel domain"
echo "- Update NEXT_PUBLIC_API_URL in Vercel to match your Azure backend"
echo "- Set up custom domains if needed"
echo "- Monitor logs in both Azure and Vercel dashboards"
echo ""

echo "🔒 SECURITY CHECKLIST"
echo "---------------------"
echo "- ✅ Environment variables are set as Application Settings (not in code)"
echo "- ✅ CORS is configured properly"
echo "- ✅ Database has proper access controls"
echo "- ✅ Redis cache is secured"
echo "- ✅ Private keys are stored securely"
echo ""

echo "Deployment guide complete! 🎉"
