---
version: "2.0"

services:
  web:
    image: smoothsend-backend:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - NODE_ENV=production
      - PORT=3000
      # Add your environment variables here
      # - DATABASE_URL=your-postgres-url
      # - REDIS_URL=your-redis-url
      # - APTOS_NODE_URL=https://api.testnet.aptoslabs.com
      # - PRIVATE_KEY=your-private-key

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    westcoast:
      pricing:
        web:
          denom: uakt
          amount: 1000
      cluster_settings:
        tolerations:
          - key: "akash.network/provider.host"
            operator: "Equal"
            value: "osmosis"
            effect: "NoSchedule"

deployment:
  web:
    westcoast:
      profile: web
      count: 1
